name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: environment-${{github.ref}}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CMAKE_CXX_COMPILER_LAUNCHER: ccache

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            libudev-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxi-dev \
            libx11-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            xvfb \
            ninja-build \
            ccache

      - name: Setup CCache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}

      - name: Add MinGW to PATH
        if: runner.os == 'Windows'
        run: echo "C:\\msys64\\mingw64\\bin" >> "$GITHUB_PATH"

      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        run: |
          C:/msys64/usr/bin/pacman.exe -Sy --noconfirm --needed \
            mingw-w64-x86_64-pkg-config \
            mingw-w64-x86_64-freetype \
            mingw-w64-x86_64-harfbuzz

      - name: Configure Debug
        run: cmake --preset debug ${{ runner.os == 'Windows' && '-DCMAKE_CXX_COMPILER=g++ -DCMAKE_PREFIX_PATH=C:/msys64/mingw64 -DSFML_USE_MESA3D=TRUE' || '' }}

      - name: Build tests
        run: cmake --build --preset debug --target build_ut

      - name: Run tests
        if: runner.os == 'Linux'
        run: xvfb-run --auto-servernum ctest --preset debug --output-on-failure

      - name: Run tests
        if: runner.os == 'Windows'
        run: ctest --preset debug --output-on-failure

      - name: Configure Release
        run: cmake --preset release ${{ runner.os == 'Windows' && '-DCMAKE_CXX_COMPILER=g++ -DCMAKE_PREFIX_PATH=C:/msys64/mingw64 -DSFML_USE_MESA3D=TRUE' || '' }}

      - name: Build game
        run: cmake --build --preset release --target game
