name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: environment-${{github.ref}}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CMAKE_CXX_COMPILER_LAUNCHER: ccache

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            libudev-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxi-dev \
            libx11-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            ninja-build \
            ccache

      - name: MSVC environment
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup CCache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}

      - name: Configure Debug
        run: cmake --preset debug

      - name: Build tests
        run: cmake --build --preset debug --target build_ut

      - name: Run tests
        run: ctest --preset debug --output-on-failure

      - name: Configure Release
        run: cmake --preset release

      - name: Build game
        run: cmake --build --preset release --target game
