name: CMake Multi-Platform Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            compiler: llvm
            c_compiler: clang
            cpp_compiler: clang++
          - os: ubuntu-latest
            compiler: gcc
            c_compiler: gcc
            cpp_compiler: g++

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install OpenGL libraries (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1-mesa-dev \
            mesa-common-dev \
            libudev-dev \
            libopenal-dev \
            libvorbis-dev \
            libflac-dev \
            libxrandr-dev \
            libfreetype6-dev \
            libglew-dev \
            libjpeg-dev \
            libsndfile1-dev \
            libxcursor-dev \
            libx11-dev \
            libxrender-dev \
            libxi-dev
            
      - name: Set up C++ environment
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true

      - name: Configure CMake
        run: cmake --preset debug -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}

      - name: Build
        run: cmake --build --preset debug

      - name: Test
        run: ctest --preset debug
